# How many repositories to pull and build at the same time, 1 to 10.
concurrency: 4
repos:
  - name: myapp
    path: ~/workspace/myapp
    build_command: cargo build
  - name: another-app
    path: ~/workspace/another-app
    build_command: npm run build
