#!/usr/bin/env bash
# Writes the licenses of the libraries compiled into pullkit to
# THIRD-PARTY-NOTICES.txt. Run it again and commit the result whenever a
# dependency is added or upgraded: the tests in src-tauri/src/main.rs check that
# the file lists every direct dependency at the version Cargo.lock picked.
#
# Only Rust crates are listed. ui/ is plain HTML / CSS / JS with no packages of
# its own, and the `window.__TAURI__` script Tauri injects into it is part of
# the tauri crate, which is listed below.
#
# Needs cargo-about: cargo install cargo-about --locked --features cli
# Configuration is in src-tauri/about.toml, the layout in src-tauri/about.hbs.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="THIRD-PARTY-NOTICES.txt"

if ! cargo about --version >/dev/null 2>&1; then
  echo "Error: cargo-about is not installed. Run: cargo install cargo-about --locked --features cli" >&2
  exit 1
fi

# Written next to the output and moved into place, so that a run which stops
# half way leaves the old file rather than a broken one. A move from /tmp could
# cross file systems and turn into a copy.
TMP=$(mktemp "${OUT}.XXXXXX")
trap 'rm -f "$TMP"' EXIT

{
  cat <<'HEADER'
THIRD-PARTY NOTICES

pullkit bundles the open source libraries listed below. Each entry gives the
license, the packages it applies to, and the license text as shipped by the
package. Generated by scripts/generate-third-party-notices.sh; do not edit by hand.

################################################################################
# Rust crates (compiled into the binary)
################################################################################

HEADER

  # --fail: a crate whose license cannot be identified fails the run instead of
  # being left out with a warning.
  cargo about generate --manifest-path src-tauri/Cargo.toml --locked --fail src-tauri/about.hbs
} > "$TMP"

mv "$TMP" "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
