//! The licenses shipped with the binary: pullkit's own and those of the
//! libraries compiled into it.
//!
//! What ships is a bare binary in a tarball, with no LICENSE file of its own
//! beside it once installed, so both texts are compiled in and shown together:
//! by `pullkit --license`, and in the GUI under the application menu's
//! "Third-Party Licenses", right after About.

use tauri::{
    menu::{Menu, MenuItem},
    AppHandle, Manager, Runtime, WebviewUrl, WebviewWindowBuilder,
};

/// Generated by `scripts/generate-third-party-notices.sh`. The tests below
/// fail when a dependency changes and the file is not generated again.
#[cfg(test)]
const THIRD_PARTY_NOTICES: &str = include_str!("../../THIRD-PARTY-NOTICES.txt");

/// pullkit's own license first, then the notices, as one text.
pub const LICENSE_TEXT: &str = concat!(
    include_str!("../../LICENSE"),
    "\n",
    include_str!("../../THIRD-PARTY-NOTICES.txt"),
);

/// Id of the menu item and label of the window it opens.
pub const MENU_ID: &str = "third-party-licenses";
const WINDOW_LABEL: &str = "licenses";

#[tauri::command]
pub fn third_party_notices() -> &'static str {
    LICENSE_TEXT
}

/// Tauri's default menu with "Third-Party Licenses" right after About.
///
/// Only macOS gets a menu (Tauri builds the default one on macOS alone), and
/// there the first submenu is the application menu, whose first item is About.
/// Written for every platform so that the Linux build type-checks it too.
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
pub fn app_menu<R: Runtime>(app: &AppHandle<R>) -> tauri::Result<Menu<R>> {
    let menu = Menu::default(app)?;
    let item = MenuItem::with_id(app, MENU_ID, "Third-Party Licenses", true, None::<&str>)?;
    if let Some(app_menu) = menu.items()?.first().and_then(|kind| kind.as_submenu()) {
        app_menu.insert(&item, 1)?;
    }
    Ok(menu)
}

/// Opens the licenses window, or brings it forward when it is already open.
pub fn show_window<R: Runtime>(app: &AppHandle<R>) -> tauri::Result<()> {
    if let Some(window) = app.get_webview_window(WINDOW_LABEL) {
        window.show()?;
        return window.set_focus();
    }
    WebviewWindowBuilder::new(app, WINDOW_LABEL, WebviewUrl::App("licenses.html".into()))
        .title("Third-Party Licenses")
        .inner_size(680.0, 600.0)
        .min_inner_size(420.0, 300.0)
        .build()?;
    Ok(())
}

/// Closes the licenses window. Called when the main window goes away: the
/// application ends with its last window, and a licenses window left open
/// would keep it, and whatever the sync was running, alive.
pub fn close_window<R: Runtime>(app: &AppHandle<R>) {
    if let Some(window) = app.get_webview_window(WINDOW_LABEL) {
        let _ = window.destroy();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The crates of this workspace. They are not third-party, and cargo-about
    /// leaves them out because they are `publish = false`.
    const OWN_CRATES: [&str; 2] = ["pullkit", "pullkit-core"];

    /// A checkout with autocrlf has CRLF line ends; the parsers work on LF.
    fn lf(text: &str) -> String {
        text.replace("\r\n", "\n")
    }

    /// The names of the dependencies that are compiled into the binary:
    /// `[dependencies]` and `[target.'cfg(..)'.dependencies]`, one-line entries
    /// only (`name = ...` or `name.workspace = true`). Build and dev
    /// dependencies do not ship. A dependency added for a target that is not
    /// released falls outside the targets in about.toml, is not in the
    /// notices, and fails the test; leave it out here if that happens.
    fn direct_dependencies(manifest: &str) -> Vec<String> {
        let mut section = String::new();
        let mut names = Vec::new();
        for line in manifest.lines() {
            let line = line.trim();
            if line.starts_with('[') {
                section = line.to_string();
                continue;
            }
            let shipped = section == "[dependencies]"
                || (section.starts_with("[target.") && section.ends_with(".dependencies]"));
            if !shipped || line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some((key, _)) = line.split_once('=') {
                let name = key.trim().trim_end_matches(".workspace");
                if !OWN_CRATES.contains(&name) {
                    names.push(name.to_string());
                }
            }
        }
        names
    }

    /// The (name, version) pairs listed under "Used by:" in the notices. An
    /// entry is a separator, `License: ...`, a blank line and "Used by:", and
    /// only that sequence starts a list, so a license text that happens to
    /// contain the same words is not read as one.
    fn packages_in_notices(notices: &str) -> Vec<(String, String)> {
        let separator = "=".repeat(80);
        let mut packages = Vec::new();
        let mut in_block = false;
        let mut after_separator = false;
        let mut after_license = false;
        for line in notices.lines() {
            if in_block {
                let mut words = line.strip_prefix("  ").unwrap_or("").split(' ');
                match (words.next(), words.next()) {
                    (Some(name), Some(version)) if !name.is_empty() => {
                        packages.push((name.to_string(), version.to_string()));
                    }
                    _ => in_block = false,
                }
                continue;
            }
            in_block = after_license && line == "Used by:";
            after_license = (after_separator && line.starts_with("License: "))
                || (after_license && line.is_empty());
            after_separator = line == separator;
        }
        packages
    }

    /// The `[[package]]` blocks of Cargo.lock: (name, version, dependencies).
    fn locked_packages(lock: &str) -> Vec<(String, String, Vec<String>)> {
        lock.split("[[package]]")
            .skip(1)
            .map(|block| {
                let field = |key: &str| {
                    block
                        .lines()
                        .find_map(|line| line.strip_prefix(key))
                        .map(|rest| rest.trim().trim_matches('"').to_string())
                        .unwrap_or_default()
                };
                let deps = block
                    .lines()
                    .filter_map(|line| line.strip_prefix(" \""))
                    .map(|line| line.trim_end_matches("\",").to_string())
                    .collect();
                (field("name = "), field("version = "), deps)
            })
            .collect()
    }

    /// The version Cargo.lock picked for `name` as a dependency of `root`.
    /// When a crate is in the lock at more than one version, the root names
    /// the one it uses as `name version`.
    fn resolved_version(lock: &[(String, String, Vec<String>)], root: &str, name: &str) -> String {
        let (_, _, deps) = lock
            .iter()
            .find(|(crate_name, _, _)| crate_name == root)
            .unwrap_or_else(|| panic!("Cargo.lock has no {root} package"));
        let entry = deps
            .iter()
            .find(|dep| *dep == name || dep.starts_with(&format!("{name} ")))
            .unwrap_or_else(|| panic!("{name} is not a dependency of {root} in Cargo.lock"));
        // `name version (source)` when the same version comes from two sources.
        match entry.split(' ').nth(1) {
            Some(version) => version.to_string(),
            None => {
                let mut versions = lock
                    .iter()
                    .filter(|(crate_name, _, _)| crate_name == name)
                    .map(|(_, version, _)| version.clone());
                let version = versions.next().expect("the crate is in Cargo.lock");
                assert!(
                    versions.next().is_none(),
                    "{name} has several versions in Cargo.lock"
                );
                version
            }
        }
    }

    /// Every direct dependency of both crates is listed at the version
    /// Cargo.lock picked. Checking the name alone would pass on an upgraded
    /// dependency whose old version is still in the tree through another crate.
    #[test]
    fn notices_list_every_direct_dependency_at_its_locked_version() {
        // Arrange
        let lock = locked_packages(&lf(include_str!("../../Cargo.lock")));
        let listed = packages_in_notices(&lf(THIRD_PARTY_NOTICES));
        assert!(listed.len() > 100, "parsed notices: {listed:?}");
        let manifests = [
            ("pullkit", include_str!("../Cargo.toml")),
            (
                "pullkit-core",
                include_str!("../../crates/pullkit-core/Cargo.toml"),
            ),
        ];

        // Act
        let mut checked = Vec::new();
        let mut missing = Vec::new();
        for (root, manifest) in manifests {
            for name in direct_dependencies(&lf(manifest)) {
                let entry = (name.clone(), resolved_version(&lock, root, &name));
                if !listed.contains(&entry) {
                    missing.push(entry);
                }
                checked.push(name);
            }
        }

        // Assert
        for name in ["tauri", "clap", "objc2", "serde_yaml", "libc"] {
            assert!(
                checked.iter().any(|dep| dep == name),
                "parsed deps: {checked:?}"
            );
        }
        assert!(
            missing.is_empty(),
            "not in THIRD-PARTY-NOTICES.txt (run scripts/generate-third-party-notices.sh): {missing:?}"
        );
    }

    /// A listed version that Cargo.lock does not have means a dependency moved
    /// and the notices were not generated again.
    #[test]
    fn notices_list_only_versions_in_cargo_lock() {
        // Arrange
        let lock = locked_packages(&lf(include_str!("../../Cargo.lock")));
        let listed = packages_in_notices(&lf(THIRD_PARTY_NOTICES));
        assert!(listed.len() > 100, "parsed notices: {listed:?}");

        // Act
        let stale: Vec<&(String, String)> = listed
            .iter()
            .filter(|(name, version)| !lock.iter().any(|(n, v, _)| n == name && v == version))
            .collect();
        let own: Vec<&(String, String)> = listed
            .iter()
            .filter(|(name, _)| OWN_CRATES.contains(&name.as_str()))
            .collect();

        // Assert
        assert!(
            stale.is_empty(),
            "not in Cargo.lock (run scripts/generate-third-party-notices.sh): {stale:?}"
        );
        assert!(own.is_empty(), "pullkit lists itself: {own:?}");
    }

    #[test]
    fn license_text_starts_with_pullkits_own_license() {
        // Act
        let text = lf(third_party_notices());

        // Assert
        assert!(text.starts_with("MIT License\n\nCopyright (c) 2026 Cyberneura\n"));
        assert!(text.contains("\nTHIRD-PARTY NOTICES\n"));
    }

    #[test]
    fn parsers_accept_crlf() {
        // Arrange
        let notices = "x\r\n".to_string()
            + &"=".repeat(80)
            + "\r\nLicense: MIT\r\n\r\nUsed by:\r\n  serde 1.0.0 (u)\r\n\r\ntext\r\n";
        let manifest = "[dependencies]\r\nanyhow.workspace = true\r\nclap = \"4\"\r\n";

        // Act
        let listed = packages_in_notices(&lf(&notices));
        let deps = direct_dependencies(&lf(manifest));

        // Assert
        assert_eq!(listed, vec![("serde".to_string(), "1.0.0".to_string())]);
        assert_eq!(deps, vec!["anyhow".to_string(), "clap".to_string()]);
    }
}
